# Generated by Django 5.0.1 on 2024-03-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
