# Generated by Django 5.0.1 on 2024-04-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.RemoveField(
            model_name='show',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='show',
            name='release_date',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='release_year',
            field=models.PositiveIntegerField(default=2006),
            preserve_default=False,
        ),
    ]
