# Generated by Django 5.0.1 on 2024-04-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actor_images/'),
        ),
    ]
